### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lxl66566** [BaggerFast/PyConsoleMenu#1]
cannot use pip or poetry to install it.
```
$ pip install PyConsoleMenu
Collecting PyConsoleMenu
  Downloading PyConsoleMenu-1.0.4.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "Z:\Temp\pip-install-fnr177mb\pyconsolemenu_6caedd7aebd74535a737fb635e684bb4\setup.py", line 6, in <module>
          long_description = (this_directory / "README.md").read_text()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\scoop\apps\python\current\Lib\pathlib.py", line 1028, in read_text
          return f.read()
                 ^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 915: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by BaggerFast** [comment]
I try to fix it, give me a time)

**Comment by lxl66566** [comment]
I made a [fork version of this repo](https://github.com/lxl66566/PyConsoleMenu2), with some breaking changes and features.

**Comment by BaggerFast** [comment]
> I made a [fork version of this repo](https://github.com/lxl66566/PyConsoleMenu2), with some breaking changes and features.

It's good idea to use a builder pattern)
